### PR TITLE
Adding XK (Kosovo) to countries.properties

### PR DESCRIPTION
**Pull request by giorgioazzinnaro**
https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/

XK has been temporarily assigned to Kosovo
I got it in some entries from SSI Plus, because SWIFT is also using this, I guess it should be reported as such in this library

### CODE REVIEW

**Comment by zubri** [comment]
Thanks. However, we have deprecated this in favor of the IsoUtils class which uses countries information from the Java Locale.

And the implementation is a singleton so if your solution is not running on a recent JRE you can always work around the lack of some codes by adding them to the static list when the application is initialized.

**Comment by giorgioazzinnaro** [comment]
Hi @zubri , I actually realised after I sent this PR, and trying it out, that it didn't really work... So I did like you said, and at runtime just injected in the IsoUtils Set all the keys from the countries.properties file.
I'm afraid though this is not about an older JRE version, but rather a country code (in this case XK, but there may be others), that's not an official ISO code, but is being used by SWIFT nonetheless.
I think this kind of "patch" for ISO codes should be provided directly by this library, given the scope.
Let me know what you think! Happy to provide a PR if you consider this useful! Cheers

**Comment by giorgioazzinnaro** [comment]
Cool stuff! Thanks!
Well it is a Set for all countries, so I actually merged the whole countries.properties file (so that it was a piece of configuration and not hardcoded, because at our company is particularly unbearable to actually make a new software release, so I'd rather change a config file if a new field comes up!)

**Comment by zubri** [comment]
You can always add the piece of configuration in your application. For the library, I think the API version is just fine.

**Pull request closed without merging**
