### PR TITLE
SRU2022 v10

### PR DESCRIPTION
**Pull request by zubri**
This PR contains the migration to Java 11 and Jakarta EE 10 for the current SRU2022.

In terms of library releases, this branch develops and maintains all prowide-core-SRU2022-10.0.x versions.

More info at https://dev.prowidesoftware.com/SRU2022/release-notes/

### CODE REVIEW

**Comment by zubri** [comment]
com.prowidesoftware:prowide-core:SRU2022-10.0.0-RC1 released

**Comment by zubri** [comment]
RC1 has been released

https://central.sonatype.com/artifact/com.prowidesoftware/pw-swift-core/SRU2022-10.0.0-RC1

Including:
* Migration to Java 11
* Migration to Jakarta EE 10

**Comment by zubri** [comment]
Release done

https://central.sonatype.com/artifact/com.prowidesoftware/pw-swift-core/SRU2022-10.0.0

**Comment by ratoaq2** [comment]
These classes are still using old javax xml bind:

https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/main/java/com/prowidesoftware/swift/utils/SafeXmlUtils.java#L24-L32
https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/main/java/com/prowidesoftware/swift/io/parser/XMLParser.java#L32
https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/test/java/com/prowidesoftware/swift/io/parser/XMLParserTest.java#L35

**Comment by zubri** [comment]
> These classes are still using old javax xml bind:
> 
> https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/main/java/com/prowidesoftware/swift/utils/SafeXmlUtils.java#L24-L32 https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/main/java/com/prowidesoftware/swift/io/parser/XMLParser.java#L32 https://github.com/prowide/prowide-core/blob/SRU2022_v10/src/test/java/com/prowidesoftware/swift/io/parser/XMLParserTest.java#L35

The classes you refer to are part of the Java SE platform and are not specific to the javax.xml.bind package. They are still available in Java 11 and later versions and do not need to be replaced with Jakarta equivalents.

**Comment by ratoaq2** [comment]
Sorry, you're completely correct. I overlooked that

**Comment by zubri** [comment]
This PR has been replaced by the SRU2023 v10 containing also the migration to Jakarta and Java 11, but with the current SRU2023 standard

**Pull request closed without merging**
